language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: XUgSA2MVjFJlsL9IlD61Rrs4t89VOCLQl25SNB9+TmkDfFPxeFeHu/Zy6kgcma8gOInRiXfmRj4Vqt86Hyud3sj+qkU0ciglnrjXeDkNHDwrFdkCsH32Dk5SoY1h/5M9NBRz9xMv3SN4IkYesf4vQSr34js905QGjspvzvfQod5OnfiiF8jX+wFE1P8dk6ZhSjDzqxbrdJSV7m8vXGXtW9PZ0gJV2qZlwSjPWrqjPZKBUwJVD9+ifrfzVF9CXVWxrc7ucjCSKAW1BpPifr6HcxwQF3sLu5tmLqFZiuIkb9134Opi0ZvxAU3mrh4WP8Er+G86R4MarkJqRAWIIR67yQ45otzdcDckfsSE0/uJcMQ33P1LkBdWusRyhFz40uuebj1Tq6Wtt/JFBqZWYxEs7/OtAURM/zwngI/s469yyM4sn7Du0TS0kNxWaHXd6dpzbaCfVEK0dJgunaj6BgJPmyk2Kc0X0cqaG4+rKmRUSAbLEXunnMhfFwQsCblSCzP4sAWfzNuizdx9pvs9sW3tanvq7V910qwgeuk2p4yCMeOLuwapJl/9MLkOUSsurH+j7rIneYneg/1Bl6VQHXjWHNQ5j5LebkuPDNIL6FnU2Rgj5IFc/2YWzVwHJRPqO48d8XYEtR+nfbYTSykwARUPy/SA2do9dcl5OJPR8D6qkEI=
  skip_cleanup: true
