language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:test:prepare
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: D246sSbl6uasiP0ppCA1ftSZEFkufxHYOdNkDKlLUVp3AGDbCTv+hAQ8ion2FruTmTsaGSvDfa/BbC82CQhC4mBuX2M9Ft4FjDVT3oHJCSmPEX6A+CDOD+2rfgTcebR10rqhvqcVgOGb5mNPBLryvH9Qt8uaDtucPr4s91y+ryPAD+rOrF/A0VQGoNsB3xFLLfPBDTsnI9lV/cZGnVbHIK6n+jYA+rOFeDysFO2G0vvNvIlyOm0xwOGjhZBpzUq7Y1EsFgIMZ9pJ7j4EDtwXJexcyXmaItw4c5s24Tg6m3h9WZ9tSwYv8kR3GiRr8kKUC7MV7syufea5VISZuWjbQ+d7B8O6Zj6WGuJJIFVHqMzgHJMVFGdjT8nV4Fcq404wKTg+egtgqybd3FYxgyHhQ1hgBqnpyJJeewuT/yJzklJvES5OnpCX5Mia+21+Qul4Zj9K+tcuFmQNPo7YZdX3TLQAxPMZ/eaVP9nOzKDk/qJxni8FlibBPhSdP6jYiNT7I5j5bUld9vJ5VKiUediP5bfAWsqrktyImaNNb1u5HP0/xYgztMRS8/BeFkj2ykSamqUNX/zEhCJdVp431pmPvPBG6uS7QzjP3lRqAGqCdj+aCeEWY4gS3FbZFg3H8zVHbCgzYL5L78Binx1zGpB6JflsPtnlJtq8rd5ceFd8s3w=
  app: acebook-insane
  on:
    repo: nicolasraffray/acebook-inSANE
