language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: ByxcQMYu78SlJyyc+3R1tgunKaksSluQc0daW0RHAHWJIPd+75y62x6eX03YTdf2Gl0FmbQ7Z58apKploq4H1L/p+9JClSAqKD/oFDNsQBmVBs67c+eZll7+eoTcYXr1MKoNAuv+RtsTqQEGzoFLrjKd6uXuq13SiROpN7QQOf66eaAVGM3ChfCuHk7HBa5xQTj3Rx+m1Cp+ayE9n0a4mCNQYPzY4jKgE9xHGIvHMS844knSH6KJpxYrGItgHXeEi2KkaFoKiLiubny9SwBcpwZEKU1z0s4pwkF3hDg+vBlzQuTofJONbBQqWT0+0KOSZuLNkq6nbIrhQFGJ49BZlvCsrClxGlyT5chOWhGsYgBhcfl5/fxsi0NRaMFBV+V8x9V7LXBwWQ4JlHjL/5E2bGvztGSFM3nxNDLK3BsghoC3oLcz6cfKjj7hqz19LVUBYjRlNN3t/sNckcJFGQ6kV58LT+vxXDr1aVwenEh37JoE5OG1AKS2ey7+NQL7Er79TQw57D5/6cOytP90Oq6weD7VZzGOG3mqJixLmQZC0ge+3dzurFntleQn7rwyEpg4r8/OxV88TygVN+dm9KqUTJF5akOItqT1Idcmu9SRwCzPYDVns/DW76ItYqIhJPLJS2tKINPMwemichAsszmeK1S2TWeUJF2HRS4DRdjkNFw=
  skip_cleanup: true
