language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: W0LVHVE7vYllnRy3rpqCcDLlID5LFv/GxKI5GUvFJ6limm4iZ2kNW7jPl9mADbusyd2DOInnosJzdS7H+o8zfBde6JOxhwQQS3+LkaMsaTdTzaOXkuANVvLTTJJrLYsb7tcCO3gKPjRlRKFKsRXPQ15odEeRhuJBTJ4eYbvxJn1CNpORabDhCA7+QLER1I7SmvdH2bdH5Uh7R6va/RjWreMrrfZfwF0cYDPavmA+rO0QiFdJJzvZwEQ8ff5EWOXmvx9Oolfohmf4lmMFPPKrteSmG3Ql0DZvKzFoOg4RmQmG/iC+gveEIc++sN1yQ+lLL5CwXJ+Q311B3dDNRNdy0NUI2KD1L/lcw9ex05kOycDgunhitf2vd4BKAL8bCM0ls7JXU2cpGPvkJYrqQ8ShpKxLNmXOsOOz/sqCX4yUgb8pketQGD6gAMqzRLhXz/5D3ZLzv9a5ZGUd3Th1gbUV+fOWGYSJr5wOjscdykndVOUep8gFMsrjBXDsAL9YqleXC9xZgGtLgBhQVvA1dayZR4hb82lnrVsLL+wpRbZmk0xm1ezT594/HYnv1OelcEYff5xBgTNBxKSwvkjd//nC3ivTiMEJ6lpdcOnqUp8uQpv9SDV709+XIuufTJtHQgu3c0B8Wij/d/m2/FgIP5tpzBbo0Cc7ke/lTbImJMz3vT4=
  app: acebook-insane
  on:
    repo: nicolasraffray/acebook-inSANE
