language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: QL2IeuNh+xV8AX/vOnxzLl5+CFvqlytgXZL1w3DhZ+HGK2y9AJQOgbHvOOPr+QQM/D5HT+/IZnldkYWN1/VLiGZRFTD5uwtREzhltPnN+zlrhiFKjRGrDxFKFp+36VBGiFvLByxdOYq49PTUQXQUKdCydc4LRjnC9TblkwZnOhJeT9F5MXED7Z4FC+Cun6XkE5xhZcv5Pyz67UmbokPsyztou25efNOniiyLkCciJpc+pCTUb0z4A/5NObOOlDlT8BuQJGXQn4u4tdqx0WbqiIXo4NvFfx1+mL6EpE+ZlIviJ2Pica4eRJHhg6PU3LlufdSQThtH4vywjABOi2HMo9AQ7fR98VlZHnbhfd4yNZbdtK90bu5XynvxHEdZ8pg39HpyyUvKPBL825g1repGtYiiRb2OHUZhJf8MoKnEVCjWrHa1JXpzndd/wsp9q8c8iY+v3q5Q671vdefZfKOqMa7W4u0O7bbULNLus5ey5Ka34VA7NZyANowI2gmOt9ZNuir2PvNYpaX4DrLF++Wm1sS2VDtdpB/YsdcjFdzZ+PoKTD1qru7xqHcsr7WApBoOLehZ92gfE9BeIQ2U6va5Im1TSlQPEsSq/ZexoFGAR74vjZ+8iScOVGwQdHxCV/wa2XBUlOa6PWeoPe+3udo9B/l5SvtKTYR2fjFHfY2Ya/g=
  skip_cleanup: true
