language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:test:prepare
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: ZkWiJ/YvZH96f5ePrCrVNnGlfZ1Mnmx0TkxqNSUXWdu1tgcP5fqwG0xMs54smudtzG/2MKWowhQIlXgK9Hs+LZhBLlpGdw9F1JFY+kjbTa3TWEnYpbDftNXRi6Nf6bYdVPrWlxQPJI7c8IClpj1gO/I7FL+GDut0ZHa/RNF3C1DVaD0BEMnyLiHCRUfaE96hkeZIfnIVatIjscq759LONlAhBXNOT/knD6IJum3Mpmqsh5r7S+hLt8BChZkmFrw+fvmCZaAaFZm7I8rICAYz5gwKchEQxoR9qD0ml1bGNAX1VGpk4SgBBNE3n6gIsf8vkR8xtWAWKIyA2aR0ShP4peiQuXqgNsV/SH3ihcJJ/NoIAUoKIXHiJVWgEdyc9Jig6AjUM/ovOm87WxXHcxzP0Cur5P3Wm3SnFHsrkRSQz8S7L8kSolgwfYau/hxqrWlzikWz7wjMceD1bqcasGOITWOuNTVCsV8FI+Dk3kXHUDxOMUrxBg9RDIaUAPSJpZwMKj68h2ZnyaH/Sa2cusj5ZyHKDwpSKp+MCKJsjbLcApe3s0NkWic0VY6JuNtcFfRkgMmmxfhyxi01NXDOJi098UiYH9rE2MpJdWpVQxHswLwehT9FwnoWS9NNdyBPeExWtzb4IwCdqvHwtiqYfwMOLVo2lvrgEMXAJSH9OaVRYME=
  app: acebook-insane
  on:
    repo: nicolasraffray/acebook-inSANE
