language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: XVMv7Kh913iRYRdpy+ukAi9Wy1djMy+up5UT244jqQkKaRNcEfH1UHXyv0vinO8VRZQw9bsru7JCTdJV8eBj4eOH+bjol59HJ2pOBl7bZ9u0eor21J26r6rBb3+eVJYVuki6HDhok8Giba3mvMY1n3AUFnQEdKFqP0d0dZEZqXiiy93/oWgLlX4yYgLHPyj2ItEtd8GN+//ceU/5IgEoNxRoiBo4IBMdxZLG6Skr7xUQPyaz1bGssI79Ys0t15E8TrgiBv0tjJMcH/aBcNm4eeq8ege9BjA0F8dWXtQNbbpPQTKmA3OSu9AeW7kKg4/HIkIaA8uZV9b3uKM9/+ZkUFJqVqOELhUQqH/c7Jy9owV3QbhJ5wuGvun4nQWkAbh9RDOB17pIpQBry2CnuadPWF8OAvF2CLFuh/Nr7IPG3RHIikTrtpMbx7kcxk6osFNv6pv7EYn8xBTVIIwyYkty32vdpzZtcVZsdRKrzocqAIqfhxXMVPjAkT9rjZL1M5KZ0L95bIuVtUvjIIgyliGVnLReJ1VXl8+mpXlNJwVr29iKIixpjpyrDCnAWuI3OF7t6eN4mnvXa1hnXvImppnVloNBLBGm3szcQU6z2XcuESCzeXZTd6mafJlHeX6aq/TmRKln5xxN8N18VOOXxY/ReCMo8qZoA7yrS4OBP8g1PQI=
  app:
    develop: acebook-inSANE
  skip_cleanup: true
  on:
    repo: nicolasraffray/acebook-inSANE
    branch: master
