language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: WxN+iBjZJKrQ+uvF/aew+ZfxigSUu+b4pDrXkZCjX8i6+gIzeGU7VhZF1Vn1jp4CjEwnX+ltsySR2flsKhLUYDxuc3Tbt5eNDs73/sbk6y2QKyFKMOUg/9wRtFpzTgIRMZ1V1qsOYz7eo2vqs/KwEFTOZCWPPheY7HEabIN/wfOOwfYWbdKbdw3iZO3p1OGHPkiN7tXTkm+HUW2CyxRvrbIhvrx1jxjU+nwEnomslUPWbWoUSU6FAb+QHmdG/EJJYQj7EIiai1uJ14SnJ4y2di7AIkS+Yf0eBAO4DTdPpecu9mQPjO9Qf0ZDNKkgoO93ORlZWaPT1ed0/avp87FkFKs2IknS916zrDznKLtWG3f57egu9NXd6en5bk4PgCDUz9xFC21D0Qy5kpVBI0wMXQcAih0qwo+ZjhVFN5L8qnvAyVitTZci8nxpSWvst+yqfKuhZU3UroT5xvp1dNrRk7uO/FsfLVafa+3PnwMGPE+aVvuz4ScWT+A9QYUjTHD+Cbki7EdYR+2UIWPnoRqp2u265dNuYA/NlqbAqsdH1fCCNwKDItZfU4uMYfp5gkCtkD4f4ZkGnqcyD8DBgFvyJwwSN4lwjJ1MEi7IMuN4nGoimDuTLpz4kj7A6i+s5RCwDNsm+GpiaLJ9QTDEsWKcE71ogKGYx8MOnCovCBXWMZE=
  app: acebook-insane
  on:
    repo: nicolasraffray/acebook-inSANE
